name: amplify_todo_riverpod
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  amplify_api: ^1.0.0-next.5+1
  amplify_flutter: ^1.0.0-next.5+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  go_router: ^6.2.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
