name: demo_amplify
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  amplify_api: ^1.6.2
  amplify_flutter: ^1.6.1
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
